export enum Status {
    WAITING_PAYMENT = 'WAITING_PAYMENT',
    PREPARING = 'PREPARING',
    IN_TRANSIT = 'IN_TRANSIT',
    DELIVERED = 'DELIVERED',
    EXCHANGE_REQUEST = 'EXCHANGE_REQUEST',
    ACCEPT_EXCHANGE_REQUEST = 'ACCEPT_EXCHANGE_REQUEST',
    EXCHANGE_RECEIVED = 'EXCHANGE_RECEIVED',
    DENY_EXCHANGE_REQUEST = 'DENY_EXCHANGE_REQUEST',
}
